name: UI Tests

on:
  pull_request:
    branches:
      - '**/ui-test/**'
      - 'main'
  # push:
  #   branches:
  #     - '**/ui-test/**'
  #     - 'main'

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui-tests
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: ui-tests

      - name: Upload Cypress Screenshots as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: ui-tests/cypress/screenshots/
        if: always()

      - name: Upload Cypress Videos as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: ui-tests/cypress/videos/
        if: always()