name: UI Tests

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: write

jobs:
  ui-tests:
    if: contains(github.head_ref, 'ui-test')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui-tests
    
    continue-on-error: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        continue-on-error: true
        with:
          working-directory: ui-tests
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ui-tests/cypress/reports/
          publish_branch: gh-pages
          destination_dir: ${{ github.ref_name }}
          tag_name: ${{ steps.prepare_tag.outputs.DEPLOY_TAG_NAME }}
          tag_message: 'Deployment ${{ github.ref_name }}'
        if: always()

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: cypress-html-report
          path: ui-tests/cypress/reports/
        if: always()

      - name: Upload Cypress Screenshots as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: ui-tests/cypress/screenshots/
        if: always()

      - name: Upload Cypress Videos as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: ui-tests/cypress/videos/
        if: always()