name: UI Tests

on:
  pull_request:
    branches:
      - '**/ui-test/**'
      - 'main'
  workflow_dispatch:
  # push:
  #   branches:
  #     - '**/ui-test/**'
  #     - 'main'

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui-tests
    
    continue-on-error: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        continue-on-error: true
        with:
          working-directory: ui-tests

      - name: Merge and Generate HTML Report
        run: |
          npm run reports:merge
          npm run reports:generate
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cypress/reports/html/
          publish_branch: gh-pages
          destination_dir: pr-${{ github.event.pull_request.number }}

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: cypress-html-report
          path: cypress/reports/html/

      - name: Upload Cypress Screenshots as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots/

      - name: Upload Cypress Videos as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos/